### ISSUE TITLE
Friends section content missing!

### ISSUE THREAD

**Issue by AnujSsStw** [revanced/.github#13]
![Screenshot from 2023-03-16 10-27-13](https://user-images.githubusercontent.com/92370865/225521913-e3f2f891-87a0-48cb-8924-9b593d857f4a.png)

**Comment by reisxd** [comment]
Cannot reproduce.
![IMG_20230316_083630.jpg](https://user-images.githubusercontent.com/29177546/225524616-4af64e44-0cc5-4d65-9799-db22f7f81327.jpg)

**Comment by AnujSsStw** [comment]
i check on mobile as well as other browsers. It's missing for me!!!

**Comment by oSumAtrIX** [comment]
Can't reproduce either:
![image](https://user-images.githubusercontent.com/13122796/225531262-d493a3dc-2d34-4760-a9c2-04048555b741.png)
