### ISSUE TITLE
Suggestion: auto-skip members only videos

### ISSUE THREAD

**Issue by OkamiTakahashi** [ReVanced/.github#21]
Sorry if ths is the wrong place but this needd to be a thing for the app. Playlists get stuck if a video added is later changed to members only, prompting the user to pay money and join to continue. There is no way to skip these nor can I seem to remove them now. This is far too common a practice for ASMRtists now and imo is quite frankly scummy and insensituve to non-members who create playlists. Please allow us to remove the videos while stuck or auto-skip them with a patch in the near future.

**Comment by Ushie** [comment]
This should be reopened in https://github.com/ReVanced/revanced-patches, that's the correct place
