### ISSUE TITLE
So what is ReVanced exactly?

### ISSUE THREAD

**Issue by lourkeur** [revanced/.github#5]
Hi, I hope this is appropriate for this type of feedback.

Having no prior knowledge of what Vanced was, I came across this project and cannot figure out what it is trying to do. I think from a promotion perspective, it would be good to have some sort of landing page that explains it with no prior knowledge assumption. This ReadMe might be a good place for now.

I checked the pinned repositories, revanced.app which leads back here, the twitter account which isn't explanatory, and the subreddit which isn't either. I did not check the discord server, but in any case it would not be a generally open platform. I also tried to figure out what Vanced was, but their website doesn't state it either.

**Comment by oSumAtrIX** [comment]
I recommend checking out the FAQ in the #help channel of our Discord server.

**Comment by lourkeur** [comment]
Appreciate the quick response. I assume this would indeed answer my question, but my feedback still stands. Discord isn't the appropriate medium for a public-facing introduction to a free software project. It has high barriers of entry (registering an account, using proprietary software, finding an invite link that works, getting past bots, etc.) for something that could be done with a simple static webpage or a README on Github. That's why I would suggest putting an abbreviated version of your FAQ or a pitch on the README.

Please also see [Please don't use Discord for FOSS projects](https://drewdevault.com/2021/12/28/Dont-use-Discord-for-FOSS.html)

**Comment by TheJeterLP** [comment]
> Appreciate the quick response. I assume this would indeed answer my question, but my feedback still stands. Discord isn't the appropriate medium for a public-facing introduction to a free software project. It has high barriers of entry (registering an account, using proprietary software, finding an invite link that works, getting past bots, etc.) for something that could be done with a simple static webpage or a README on Github. That's why I would suggest putting an abbreviated version of your FAQ or a pitch on the README.
> 
> Please also see [Please don't use Discord for FOSS projects](https://drewdevault.com/2021/12/28/Dont-use-Discord-for-FOSS.html)

ReVanced is in an early open alpha state and is currently directed towards developers.

**Comment by oSumAtrIX** [comment]
The same FAQ is available on reddit. The post is currently not pinned.

A proper README, documentation, wiki, tutorials and lots more will follow some time. Currently we work on other parts of the project which is why it is currently lacking this paperwork which is why we welcome any outside contributions.

**Comment by lourkeur** [comment]
Understood. Fair enough. I will still point out that not all developers are on Discord, but this is not as important right now as I initially thought.

As far as Reddit it concern, maybe the sidebar could contain a link to the FAQ post.
