### ISSUE TITLE
README.md - Add an obvious link to the ReVanced documentation to the readme

### ISSUE THREAD

**Issue by 11BelowStudio** [revanced/.github#8]
Definitely worth adding an obvious link to the ReVanced documentation repository (maybe put it just under the 'socials'), so people don't need to go digging through your repositories to find it.

**Comment by oSumAtrIX** [comment]
The current list would grow too much, we would have to remove other links to compensate for that. The repo will be rendered on revanced.app anyways, for that reason this issue can be closed.
